sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-7 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  
before_script:
  - git clone https://github.com/svoboda18/android_kernel_x5_oreo kernel
  - cd kernel
  - rm -rf *.log *.zip *zImage

script: 
  - cd kernel
  - chmod +x travis-build.sh
  - bash travis-build.sh
